version: '3.8'

services:
  puppeteer-app:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    ports:
      - "80:8100"
    env_file:
      - .env
    init: true
    
    # Essential for Puppeteer on EC2
    cap_add:
      - SYS_ADMIN
      
    restart: unless-stopped
    
    # Health check
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8100/v1/ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s