import { LaunchOptions } from "puppeteer";
import { config } from "dotenv";
config();

export const optimisedBrowserArgs = [
  '--no-sandbox',
  '--disable-setuid-sandbox',
  '--disable-dev-shm-usage',
  '--disable-gpu',
  '--disable-web-security',
  '--disable-background-timer-throttling',
  '--disable-backgrounding-occluded-windows',
  '--disable-renderer-backgrounding',
  '--disable-default-apps',
  '--disable-extensions',
  '--start-maximized',
  '--no-first-run',
  '--no-zygote',
  '--disable-dev-tools',
  '--memory-pressure-off',
  '--max-old-space-size=4096',
  '--disable-images',
  '--disable-javascript-harmony-shipping',
  '--disable-client-side-phishing-detection',
  '--disable-features=TranslateUI,BlinkGenPropertyTrees',
  '--disable-ipc-flooding-protection',
  '--disable-sync',
  '--disable-background-networking',
  '--disable-plugins',
  '--disable-print-preview',
  '--disable-speech-api',
  '--disable-file-system',
  '--disable-presentation-api',
  '--disable-permissions-api',
  '--disable-new-tab-first-run',
  '--disable-new-avatar-menu',
  '--disable-component-update',
  '--disable-domain-reliability',
  '--disable-features=AudioServiceOutOfProcess',
  '--disable-features=IPH_DesktopTabGroupsNewBadgePromo',
  '--disable-features=MediaRouter',
  '--disable-hang-monitor',
  '--disable-prompt-on-repost',
  '--allow-running-insecure-content',
  '--ignore-certificate-errors',
  '--ignore-ssl-errors',
  '--ignore-certificate-errors-spki-list',
  '--ignore-certificate-errors-ssl-key-log-file',

    // CSS and resource blocking
  '--disable-remote-fonts',
  '--disable-web-fonts',
  '--disable-remote-playback-api',
  '--blink-settings=imagesEnabled=false',
  '--disable-features=AudioServiceOutOfProcess,MediaRouter',
  '--disable-logging',
  '--use-gl=swiftshader',
  '--disable-background-media-suspend',
  '--autoplay-policy=user-gesture-required',
  '--disable-features=WebRtcRemoteEventLogUpload',
  '--disable-shared-workers',
  '--disable-storage-reset',
  '--disable-tab-for-desktop-share',
  '--disable-threaded-animation',
  '--disable-threaded-scrolling',
  '--disable-partial-raster',
  '--disable-skia-runtime-opts',
  '--disable-webgl',
  '--disable-webgl2',
  '--num-raster-threads=1',
  '--enable-surface-synchronization',
  '--run-all-compositor-stages-before-draw',
  '--disable-checker-imaging',
  '--disable-new-content-rendering-timeout',
  '--disable-chromium-updater',
  '--disable-device-discovery-notifications',
  '--disable-renderer-accessibility',
  '--disable-pdf-extension',
  '--disable-remote-extensions',
  '--disable-shared-workers',
  '--disable-speech-synthesis-api',
  '--hide-scrollbars',
  '--mute-audio',
  '--disable-gl-extensions',
  '--disable-webgl-extensions',
  '--disable-webgl-image-chromium',
  '--disable-webgl-multisampling',
  '--force-color-profile=srgb',
  '--disable-color-correct-rendering'
];

export const getBrowserOptions = async (): Promise<LaunchOptions> => {
  const isProduction = process.env.NODE_ENV === 'production';

  return {
    headless: isProduction ? 'shell' : false,
    defaultViewport: null,
      executablePath: isProduction ? '/usr/bin/chromium-browser' : undefined,
    args: [...optimisedBrowserArgs],
    timeout: 60000
  }

};